name: API and Component Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.5.0
      - name: Install dependencies
        run: npm install
      - name: Run Component Tests
        run: npm run test:component
      - name: Run API Tests
        run: npm run test:api
    
