name: Build and Deploy Rucio WebUI Component Library & React App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm clean install
      - name: Run Component Tests
        run: npm run test:component
      - name: Run API Tests
        run: npm run test:api
    
